# 프로젝트 이름
spring.application.name=back-end-api

# 포트
server.port=80

# 터미널 컬러 출력(VS Code)
spring.output.ansi.enabled=ALWAYS

# 로깅
logging.pattern.console=%clr(%-5level){green} %clr(%logger{36}.%M\\(\\)){cyan}: %msg%n
logging.level.root=INFO

# 파일 업로드
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB

# 오라클 연결정보
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# SID 방식 (구버전 Oracle, 11g/12c CDB)
#spring.datasource.url=jdbc:oracle:thin:@192.168.5.12:1521:xe
# SERVICE NAME 방식 (PDB, 12c 이상 권장)
spring.datasource.url=jdbc:oracle:thin:@192.168.5.12:1521/xepdb1
spring.datasource.username=user_spring
spring.datasource.password=oracle

# MyBatis 설정
mybatis.config-location=classpath:mybatis/config/mybatis_config.xml
mybatis.mapper-locations=classpath:mybatis/mapper/*.xml

# JWT SecretKey 설정
jwt.secret.key=${JWT_SECRET_KEY}