# 프로젝트 이름
spring.application.name=back-end-api

# 포트
server.port=80

# 터미널 컬러 출력(VS Code)
spring.output.ansi.enabled=ALWAYS

# 로깅
logging.pattern.console=%clr(%-5level){green} %clr(%logger{36}.%M\\(\\)){cyan}: %msg%n
logging.level.root=INFO

# 파일 업로드
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB