import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BootstrapClient from "./BootstrapClient";
import AppHeader from "./AppHeader";
import AppMenu from "./AppMenu";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        {/* 부트스트랩 적용 컴포넌트  */}
        <BootstrapClient />

        <div className="d-flex flex-column vh-100">
          {/* 헤더 텀포넌트 부착 */}
          <AppHeader />
          <div className="flew-glow-1 container-fluid">
            <div className="row">
              {/* 메뉴바 영역 */}
              <div className="col-md-4 p-2">
                <Suspense fallback={<div>메뉴 로딩중</div>}>
                  <AppMenu />
                </Suspense>
              </div>
              {/* 페이지 컴포넌트 영역 */}
              <div className="col-md-8">{children}</div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
